### ISSUE TITLE
parseDate() function is not working properly

### ISSUE THREAD

**Issue by bemolinari** [javaito/HolandaCatalinaFw#56]
parseDate('yyyy-mm-dd\'T\'HH:MM:ss', date_time)

"date_time": "2020-02-25T07:36:49-0300"  
"date":         "2022-12-25  07:02:49"  

All test cases showed errors in conversion of minutes and year

**Comment by javaito** [comment]
The data format parameter is wrong, to identify the place where  the month is, you must put the character 'M' in uppercase, and to identify the minutes you must put the character 'm' in lowercase. So to solve the previous example you need to write the statement as next:

parseDate('yyyy-MM-dd'T'HH:mm:ss', date_time)
