### ISSUE TITLE
Query with getMillisecondUnixEpoch function does not compile

### ISSUE THREAD

**Issue by andresceccoli** [javaito/HolandaCatalinaFw#57]
Compilation fails when getMillisecondUnixEpoch is nested inside another function (be it isNotNull, if, longValue, etc), and **simultaneously given a parameter from a dynamic resource** (subquery).

Example query

```
SELECT getMillisecondUnixEpoch(birthday), isNotNull(getMillisecondUnixEpoch(birthday)) FROM address JOIN (select * from character) as c ON c.addressId = address.addressId
```

**Comment by javaito** [comment]
This issue was fixed with release 2.1.33
